<?php

namespace app\admin\controller;

use app\admin\model\AdminAuthGroupAccessModel;
use app\admin\model\AdminAuthGroupModel;
use app\admin\model\AdminAuthRuleModel;
use app\common\controller\BaseController;
use support\Request;

class Base extends BaseController
{
    protected $admin_id;
    protected $admin_info;
    protected $admin_rule;
    function beforeAction(Request $request)
    {
        parent::beforeAction($request); // TODO: Change the autogenerated stub
        $this->admin_info = session('admin');
        $this->assign('admin_info',$this->admin_info);
        $this->admin_id = session('admin_id');
        $this->assign('admin_id',$this->admin_id);
        $this->admin_rule = session('admin_rule');
        $this->assign('admin_rule',$this->admin_rule);
    }
}